### PR TITLE
Add functionality + tutorial for using LoopVectorization

### PR DESCRIPTION
**Pull request by April-Hannah-Lena**
This PR adds the file `fast_maps_using_SIMD.jl` which is a tutorial + template for using LoopVectorization to speed up BoxMaps by a factor of 1.5x-3x. 

```julia
function f_template(x)
    dx = similar(x)
    @turbo for i in 0 : N : length(x) - N
        # replace all instances of [j] to [i+j], ie
        #  x[j] ->  x[i+j]
        # dx[j] -> dx[i+j]
    end
    return dx
end
```

The PR also adds new `BoxMap`, `rk4`, `rk4_flow_map` dispatch to make all algorithms automatically work as they used to.

### CODE REVIEW

**Comment by April-Hannah-Lena** [comment]
Tests need to be moved to Julia >1.6.0 since versions of LoopVectorization compatible with Julia 1.4 do not have the turbo macro

**Comment by April-Hannah-Lena** [comment]
It seems that the version using LoopVectorization is less accurate, to achieve similar accuracy with the normal version more test points and smaller boxes are needed.

**Comment by gaioguy** [comment]
> It seems that the version using LoopVectorization is less accurate, to achieve similar accuracy with the normal version more test points and smaller boxes are needed.

Interesting - but it shouldn't, right? I guess we need to investigate this further ...

**Comment by April-Hannah-Lena** [comment]
[Here](https://github.com/April-Hannah-Lena/GAIO.jl/blob/08ff886ff70901b0ac316ac1a10468a5acbb37bb/benchmark/LoopVectorization_bench.jl) is a quick testing setup. It seems the only thing that is broken is the `point_to_key` part ... even though I didn't touch it? Weird

**Comment by gaioguy** [comment]
`FB2 = map_boxes(F2, P[x])` fails with `nested task error: MethodError: no method matching VectorizationBase.VecUnroll(::Tuple{VectorizationBase.Vec{8, Float64}, Float64})` for me ...

**Comment by April-Hannah-Lena** [comment]
That's also strange... are you running the test on the current master branch? That shouldn't happen on April-Hannah-Lena/GAIO.jl@acbfdbd7db96413b98dc5b288183a281d642a382

**Comment by April-Hannah-Lena** [comment]
I found the issue... it seems Julia doesn't know how to broadcast a `Vector` and `SVector` together in this situation. Removing the @turbo macro and adding some debug info:

```julia
function GAIO.map_boxes(g::SampledBoxMap{N,T,Val{:cpu}}, source::BoxSet) where {N,T}
    @debug "using :cpu accel"
    P, keys = source.partition, collect(source.set)
    image = fill( Set{eltype(keys)}(), nthreads() )
    out_points = fill( SVector{N,T}[], nthreads() )
    @threads for key in keys
        box = key_to_box(P, key)
        c, r = box.center, box.radius
        points = deepcopy(g.domain_points(c, r))
        points_vec = reinterpret(T, points)
        # ---- here is the important part ----
        @debug " " type=typeof(points_vec) vec_size=size(points_vec) rest_c=size(points_vec).%size(c) rest_r=size(points_vec).%size(r)
        #= @turbo =# @. points_vec = points_vec * r + c
        # ------------------------------------
        points_vec .= g.map(points_vec)
        points = reinterpret(SVector{N,T}, points_vec)
        push!(out_points[threadid()], points...)
        for p in points
            hit = point_to_key(P, p)
            if hit !== nothing
                push!(image[threadid()], hit)
            end
        end
    end
    return BoxSet(P, union(image...)), vcat(out_points...)
```

results in `DimensionMismatch("arrays could not be broadcast to a common size")` even though the debug output shows 

```
┌ Debug:  
│   type = Base.ReinterpretArray{Float64, 1, SVector{2, Float64}, Vector{SVector{2, Float64}}, false}
│   vec_size = (128,)
│   rest_c = (0,)
│   rest_r = (0,)
└ @ Main c:\[-]\LoopVectorization_bench.jl:76
```

This means that even though the size of `r` and `c` perfectly divides `points_vec`, julia doesn't know how to broadcast it. A simple (but not as elegant) fix is to hard-code the broadcasting into a loop

```julia
#= @turbo =# for i in 0:N:length(points_vec)-N, j in 1:N
    points_vec[i+j] = @muladd points_vec[i+j] * r[j] + c[j]
end
```

This alleviates all the errors ( on both my machines ;) ), and also fixes the problem of the LoopVectorization version seeming less accurate. 

The change is commited on April-Hannah-Lena/GAIO.jl@055d019898970507500bd541cb12d64ea402444a. I can push the commit (without the debug files `LoopVectorization_bench.jl` and `LoopVectorization_3d_bench.jl`).

**Comment by gaioguy** [comment]
Ok, with a `@time` in front of `unstable_set!` in `fast_maps_using_SIMD.jl` I get
```
julia> include("fast_maps_using_SIMD.jl")
  2.667513 seconds (29.07 M allocations: 3.154 GiB, 13.32% gc time, 14.44% compilation time)
```
with the `:cpu` flag set, while I get
```
julia> include("fast_maps_using_SIMD.jl")
 45.592123 seconds (857.53 M allocations: 25.731 GiB, 9.29% gc time, 0.20% compilation time)
```
without the `:cpu`-flag.  This looks a nice speed up - but the non-`:cpu` version also does > 20x more allocations.

On the other hand, with the standard GAIO master branch, we have
```
julia> include("unstable_manifold.jl")
  0.388874 seconds (447.91 k allocations: 25.164 MiB, 13.65% compilation time)
```
It seems to me like switching to `(S)Vector`s from `Tuple`s still seems to introduce a lot of unnecessary allocations ...

**Comment by April-Hannah-Lena** [comment]
I don't get the large number of allocations when I run it, but the version using LoopVectorization isn't much faster either. I think the problem is that I've always been working under the assumption that you need to allocate space for all the test points each time you want to map test points. The paper I used all the way back in december also made this assumption. But that's not true in this case, so the time spent allocating always destroys the performance benefits of unrolling the function this way. 

I have another idea that still uses 2 out of 3 techniques described in that paper, but avoids too much allocating. This goes in a slightly different direction, but it would be automatic and it gets rid of the need for `SVectors`. You're right, they seem to be unnecessary here.

**Pull request closed without merging**
