### PR TITLE
Transferoperator in Compressed Sparse Column format

### PR DESCRIPTION
**Pull request by April-Hannah-Lena**
As mentioned in #72 this is the PR for TransferOperator using CSC format. This is also not tested yet, I will continue to update.

### CODE REVIEW

**Comment by April-Hannah-Lena** [comment]
good news: 
* SplitOrderedCollections has been added to the julia general registry after the mandatory waiting time of 3 days. 
* A working build of the CSC TransferOperator is now up. One can now run
```julia
using GAIO

# the Lorenz system
const σ, ρ, β = 10.0, 28.0, 0.4
v((x,y,z)) = (σ*(y-x), ρ*x-y-x*z, x*y-β*z)
f(x) = rk4_flow_map(v, x)

center, radius = (0,0,25), (30,30,30)
P = BoxPartition(Box(center, radius), (128,128,128))
F = BoxMap(f, P, no_of_points=200)

x = (sqrt(β*(ρ-1)), sqrt(β*(ρ-1)), ρ-1)         # equilibrium
W = unstable_set!(F, P[x])

T = TransferOperator(F, W)
(λ, ev) = eigs(T)

μ = ev[1]
T * μ ≈ μ
```

I also realized that the CSC version has the advantage of being factorizable, that is, decompositions like QR are built-in to SparseArrays.jl. Of course, there are some caveats that we should probably discuss though.

**Comment by April-Hannah-Lena** [comment]
Ok you can now run the above code, plus the extra lines:

```julia
μ = ev[1]
ν = deepcopy(μ)
ν[160228] = 1.0 # add value to some random box outside the set
η = T * ν
```

The invariant part remains invariant (as expected), but the new box causes the support to grow (also as expected).

**Comment by gaioguy** [comment]
Ok, the transfer operator works again, but there still seems to be a conflict that must be resolved before we can merge this.

**Comment by April-Hannah-Lena** [comment]
I'm working on resolving conflicts right now, this PR will be scratched in favor of one which more aligns with the master branch

**Pull request closed without merging**
