### PR TITLE
Adaptive BoxMap

### PR DESCRIPTION
**Pull request by gaioguy**
Some intial thoughts in order to adress #31. Ultimately, this should lead to an `AdaptiveBoxMap` which generates sample points in each box based on local Lipschitz estimates.

### CODE REVIEW

**Comment by gaioguy** [comment]
I am confused - why did this not end up in an empty PR?

**Comment by cafaxo** [comment]
This is interesting.
It seems that your branch contains an old commit (080f66a5a978eb8521b3122a99e6aba4eacdd484) which no longer exists in master.
Therefore, Github decided to copy the comments on that old commit into this PR. Not sure if this is a bug or feature of Github.

**Comment by cafaxo** [comment]
The quickest way to fix this, would be the following:
```
git fetch
git checkout adaptive_boxmap
git reset origin/master --hard
git cherry-pick 5470a18487e3a55690a2b1c57a5f1cfef9b0f3b0
git push --force
```

**Comment by gaioguy** [comment]
Worked like a charm - thanks! I also edited the commit message accordingly. I am going to fix the failing test.

**Comment by cafaxo** [comment]
Hmm... something weird seems to be going on with your Git.
Both "fix failing test" commits have the same parent (8dbe51073b0d551308938f181caab84116407714) and one if the "fix failing test" commits already contains the changes of the other one.
This should not happen by default...
Did you use `git pull` during the time creating these commits?

In that case, maybe
`git config --global pull.ff only`
can improve things.

**Comment by gaioguy** [comment]
Yes, I did, since after amending the first commit (64d87637d6d02c1f0028d4c34d630bf1fc785ffa) I got the git message
```shell
 ! [rejected]        adaptive_boxmap -> adaptive_boxmap (non-fast-forward)
error: failed to push some refs to 'git@github.com:gaioguy/GAIO.jl.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
```
I was actually confused by this (why should the remote branch contain anything beyond my local one?), but pulled as recommended and then pushed.

**Comment by cafaxo** [comment]
Aha! After you locally changed the commit, the histories of the remote and local branch "diverged". Git does (by default) not allow "pushing" such a diverged history. The `git pull` then created all the mess (merge commit, etc.)
The correct thing to do would have been
`git push --force`

**Comment by gaioguy** [comment]
I see - thanks.

**Comment by cafaxo** [comment]
The recommendation of `git` to use `git pull` is correct in the situation that multiple people are working on the same branch. Then you wouldn't want to overwrite each other's work by force-pushing. Instead, `git pull` then merges the work into your local branch.

**Comment by gaioguy** [comment]
Yes, that makes sense. But here, there hasn't been any change in the remote branch between my two local commits (or rather between my commit and its amendment), that is why I got confused.

**Comment by cafaxo** [comment]
Let's see. Before you amended the commit, we had the following situation:
remote:
8dbe51073b
\\
64d87637d6d02c1f

local:
8dbe51073b
\\
64d87637d6d02c1f

Once you amended the commit, we have
local:
8dbe51073b
\\
0196b994a983b576

At this point, the remote and local have "diverged": There is no way to (safely) combine the "remote" and new "local" trees without a commit that has two parents. This is exactly what `git pull` did: It created a commit that has as parent both 64d87637d6d02c1f and 0196b994a983b576.
What you wanted instead was

remote:
8dbe51073b
\\
0196b994a983b576

You can get that by force-pushing.

**Comment by gaioguy** [comment]
I see.  So the merge commit got necessary because I amended my last local commit instead of generating a new one?

**Comment by cafaxo** [comment]
If you created a new commit, we would have the situation

remote:
8dbe510
\\
64d8763

local:
8dbe510
\\
64d8763
\\
<new commit>

These two trees can by combined safely without creating any new commits (just take the local tree).
So yes: A new commit would have allowed you to simply "git push".

**Comment by cafaxo** [comment]
By the way, you can fix everything by just doing
```
git reset 0196b994a983b57657719cebf6a41e14e193c82b --hard
git push --force
```

**Comment by gaioguy** [comment]
Indeed - nice and clean now, thanks.

**Pull request merged**
